# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_factors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlebaroption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='saddleoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
