# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_factors', '0002_auto_20160713_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component_factors.Category', verbose_name='Bike types that this feature is avalable for')),
            ],
            options={
                'ordering': ['option'],
            },
        ),
        migrations.AlterField(
            model_name='handlebaroption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='saddleoption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
