# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_factors', '0003_auto_20160718_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryOption',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemOption',
        ),
    ]
