# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_factors', '0005_auto_20160719_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandlebarOption',
        ),
        migrations.DeleteModel(
            name='SaddleOption',
        ),
    ]
