# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_donations', '0004_auto_20160713_2124'),
        ('bike_factors', '0002_auto_20160712_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheeloption',
            name='requisites',
        ),
        migrations.DeleteModel(
            name='WheelOption',
        ),
    ]
