# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_factors', '0003_auto_20160713_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeoption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='brandoption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
