# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_factors', '0004_auto_20160715_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticoption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='featuresoption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='frameoption',
            name='option',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
