# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bike_factors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nego_factor', models.DecimalField(decimal_places=2, default=1.05, max_digits=3)),
                ('bike_price', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('bike_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_factors.BrandOption')),
                ('bike_cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_factors.CosmeticOption')),
                ('bike_features', models.ManyToManyField(blank=True, to='bike_factors.FeaturesOption')),
                ('bike_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_factors.FrameOption')),
                ('bike_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_factors.BikeOption')),
                ('bike_wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike_factors.WheelOption')),
            ],
        ),
    ]
