# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_donations', '0002_auto_20160712_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='frame',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bike_factors.FrameOption'),
        ),
    ]
