# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_donations', '0005_component'),
        ('bike_donations', '0005_auto_20160714_1545'),
    ]

    operations = [
    ]
