# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('component_factors', '0005_auto_20160719_1635'),
        ('bike_donations', '0006_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='handleSelect',
        ),
        migrations.RemoveField(
            model_name='component',
            name='saddleSelect',
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_factors.CategoryOption'),
        ),
        migrations.AddField(
            model_name='component',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='component_factors.ItemOption'),
        ),
    ]
