# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_inventory', '0002_auto_20160721_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsku',
            name='customSku',
            field=models.CharField(max_length=11),
        ),
    ]
